


const questionstask2 = [
  "Should wealthy nations be required to share their wealth with poorer nations by providing them with things such as food and education? Or is this the responsibility of the governments of poorer nations to look after their citizens?",
  "Some people believe that technological advancements have led to the breakdown of family communication. To what extent do you agree or disagree?",
  "In many countries, the gap between the rich and the poor is widening. What problems does this create? What solutions can you suggest?",
  "Some people argue that it is more important to have an enjoyable job than to earn a lot of money. Do you agree or disagree?",
  "Nowadays, more and more young people are getting involved in crime. What are the reasons for this? What solutions can you offer?",
  "Some people think that students who don’t take a break in studies between the high school and the university are at disadvantage compared to students who travel and work after high school before further continuing their education. Do you agree or disagree?",
  "Some people think that parents should teach their children how to be good members of society. Others, however, believe that school is the best place to learn this. Discuss both views and give your own opinion.",
  "There is no longer enough natural resources to sustain current levels of economic growth. To what extent do you agree or disagree with this statement?",
  "We are becoming increasingly dependent on computers. They are used in business, crime detection and even to fly planes. What things will they be used for in future? Is this dependence on computers a good thing or should we be more suspicious of their benefits?",
  "There is no longer enough natural resources to sustain current levels of economic growth. To what extent do you agree or disagree with this statement?",
  "Some say that the Internet is making the world smaller by bringing people together. To what extent do to you agree that the Internet is making it easier for people to communicate with one another?",
  "Nowadays environmental problems are too big to be managed by individual persons or individual countries. In other words, it is an international problem. To what extent do you agree or disagree?",
  "What are the arguments for and against capital punishment? Discuss the debate surrounding capital punishment, considering both arguments for and against it.",
  "Should wealthy nations be required to share their wealth with poorer nations by providing them with things such as food and education? Or is this the responsibility of the governments of poorer nations to look after their citizens?",
  "Without capital punishment our lives are less secure and crimes or violence increase. To what extent do you agree or disagree with this opinion?",
  "Some people think that they can learn better by themselves than with a teacher. Others think that it is always better to have a teacher. Which do you prefer? Use specific reasons to develop your essay.",
  "Nowadays people like to change their day by day activities according to the latest trends and also they are following popular things what their surrounding peoples make them popular in their area. This essay will explain the reason why the people are spending more time for popular hobbies rather than their individual activities.",
  "Universities should allocate the same amount of money to their sport activities as they allocate to their libraries. Do you agree or disagree?",
  "Modern medicine helps to live a longer life. Do you agree?",
  "Boys are most influenced by their fathers and girls are most influenced by their mothers. Do you agree or disagree? Use specific reasons to support your opinion.",
  "Some people believe that having a pet such as a cat or a dog helps old people to live a more enjoyable life and to stay healthier. How do you think old people benefit from having a pet? Do you think there are any problems related to old people who have pets?",
  "Some people think that it is important to use leisure time for activities that develop the mind, such as reading and doing crossword puzzles. Others feel that it is important to give one’s mind a rest in leisure time. Discuss.",
  "Most high level positions in companies are filled by men, even though the workforce in many developed countries consists of 50 percent female workers. Companies should be required to allocate a certain percentage of management positions to women. Discuss, what is your opinion?",
  "The world is experiencing a dramatic increase in population, which is causing problems not only for poor, undeveloped countries, but also for industrialized and developed nations. Describe some of the problems that overpopulation causes, and suggest at least one possible solution. You should write at least 250 words.",
  "Some people say that the education system is the only critical factor to development of a country. To what extent do you agree or disagree with this statement?",
  "People attend college or university for many different reasons (for example, new experiences, career preparation, or to increase knowledge). Why do you think people attend college or university? Use specific reasons and examples to support your answer.",
  "Dieting can change a person’s life for the better or ruins one’s health completely. What is your opinion?.",
  "Even though globalization affects the world’s economy in a very positive way, its negative side should not be forgotten. Discuss.",
  "Financial education should be a mandatory component of the school program. To what extent do you agree or disagree with this statement?",
  "Dieting can change a person’s life for the better or ruins one’s health completely. What’s your opinion?",
  "Nowadays celebrities earn more money than politicians. What are the reasons for this? Is it a positive or negative development?",
  "Crime rates are likely to decline due to the advancements in technology, which will help prevent and solve crimes in an easier way. Do you agree or disagree?",
  "Many people argue that museums and art galleries should present the nation’s art, as opposed to artworks from other countries. To what extent do you agree or disagree?",
  "As computers are being used more and more in education, there will be soon no role for teachers in the classroom.",
  "Education in financial management should be a mandatory component of the school program. To what extent do you agree or disagree with this statement? Give reasons for your answer and include examples from your experience.",
  "Scientists believe that the world is in danger due to environmental changes. Some people say that personal lifestyle changes should be made to reduce the damage to environment, while others think that the government should do something to help. Discuss both views and give your own opinion.",
  "Modern children are suffering from the diseases that were once considered to be meant for adults only. Obesity is a major disease prevalent among children. What are its causes and what solutions can be offered?",
  "Nowadays people waste a lot of food that was bought from shops and restaurants. Why do you think people waste food? What can be done to reduce the amount of food they throw away?",
  "Some people believe that teaching music in schools is a vital part of growing up and the human experience, whilst others believe that teaching music in schools is a waste of time and resources. Discuss both these views and give your own opinion.",
  "Although the prices of fuels have greatly increased over the last decade or two, it is argued that further increases in fuel prices are the only way to reduce world consumption of fuel and lessen pressure on the world’s fuel resources. To what extent do you agree or disagree with this statement?",
  "Many parents give jobs to their children to do around the house in order to develop their characters and self-sufficiency. Discuss this idea and give your opinion.",
  "Some people today believe that the world’s increase in population is unsustainable and will eventually lead to a global crisis. Other people believe that world population increase is necessary and beneficial as it creates the growth of the world’s economy and society. Discuss both these views and give your opinion.",
  "It seems clear that obesity in today’s society is to some extent due to the availability of fast food. Should governments place a tax on fast food to reduce the amount of fast food consumed? ",
  "Today’s society provides people with various ways to lose weight, such as special diets or exercise regimes. Many people believe though that poor food and today’s lifestyle should be addressed first. What is your opinion?",
  "One of the major problems that faces today’s governments is creating enough satisfactory housing for their increasing populations whilst still trying to protect the environment. How can this be achieved? Discuss and give your opinion",
  "The breakthroughs in medical science are by far the most significant advances in world society over the last two centuries. Discuss this statement and give your opinion.",
  "Some people think that sending criminals to prison is not effective. Education and job training should be used instead. Do you agree or disagree?",
  "In many countries, children are becoming overweight and unhealthy. Some people think that the government should be responsible for solving this problem. To what extent do you agree or disagree?",
  "Some people think that zoos are cruel and should be closed down. Others, however, believe that zoos can be useful in protecting wild animals.",
  "Some teachers think that changing subjects with every lesson will help their students focus more. However, other teachers think that offering their students several lessons on the same subject in a row will help them focus more. Which opinion do you think is better?",
  "Some people think that men and women have different qualities, therefore certain jobs are suitable for men and others for women. To what extent do you agree or disagree?",
  "Being a celebrity can bring benefits and problems at the same time. To what extent do you agree on this statement?",
  "Some people say that now we can see films on our phones or tablets, there is no need to go to the cinema. Others say that to be fully enjoyed, films need to be seen in a cinema. Discuss both views and give your opinion.",
  "Criminality is growing among children and teenagers. Why is it growing and how should these criminals be treated?",
  "Please elaborate on your current physical and mental health, including any dental or oral treatment, medical interventions, and mental health therapy or counseling.",
  "Some people say that protecting the environment is the government’s responsibility. Others believe that every individual should be responsible for it. Discuss both views and give your own opinion.",
  "Some people think that it is better to educate boys and girls in separate schools. Others, however, believe that boys and girls benefit more from attending mixed schools. Discuss both views and give your opinion."
];



export default questionstask2;